import { getUnixTime, addDays } from "date-fns";

export const events = [
  {
    title: "Meeting 1 asdfasdfasdfasdf",
    date: new Date(),
    startTime: "10:30",
    endTime: "11:00",
    id: 1,
    category: "Meeting",
    description: "Meeting 1",
    location: "Room 1",
    createdBy: "Kwan Yee",
    attendees: ["Kwan Yee"],
    createdAt: getUnixTime(new Date()),
  },
  {
    title: "Meeting 1 asdfasdfasdfasdf",
    date: addDays(new Date(), 1),
    startTime: "10:00",
    endTime: "12:00",
    id: 2,
    category: "Meeting",
    description: "Meeting 1",
    location: "Room 1",
    createdBy: "Kwan Yee",
    attendees: ["Kwan Yee"],
    createdAt: getUnixTime(new Date()),
  },
  {
    title: "Meeting 1 asdfasdfasdfasdf",
    date: addDays(new Date(), 2),
    startTime: "10:00",
    endTime: "12:00",
    id: 3,
    category: "Meeting",
    description: "Meeting 1",
    location: "Room 1",
    createdBy: "Kwan Yee",
    attendees: ["Kwan Yee"],
    createdAt: getUnixTime(new Date()),
  },
  {
    title: "Meeting 1 asdfasdfasdfasdf",
    date: addDays(new Date(), 3),
    startTime: "01:00",
    endTime: "10:30",
    id: 4,
    category: "Meeting",
    description: "Meeting 1",
    location: "Room 1",
    createdBy: "Kwan Yee",
    attendees: ["Kwan Yee"],
    createdAt: getUnixTime(new Date()),
  },
  {
    title: "Meeting 1 asdfasdfasdfasdf",
    date: new Date(),
    startTime: "01:15",
    endTime: "11:30",
    id: 5,
    category: "Meeting",
    description: "Meeting 1",
    location: "Room 1",
    createdBy: "Kwan Yee",
    attendees: ["Kwan Yee"],
    createdAt: getUnixTime(new Date()),
  },
  {
    title: "Meeting 1 asdfasdfasdfasdf",
    date: new Date(),
    startTime: "01:00",
    endTime: "12:00",
    id: 6,
    category: "Meeting",
    description: "Meeting 1",
    location: "Room 1",
    createdBy: "Kwan Yee",
    attendees: ["Kwan Yee"],
    createdAt: getUnixTime(new Date()),
  },
];
